### ISSUE TITLE
joss/editing

### ISSUE THREAD

**Issue by soodoku** [JannisHoch/copro#102]
"The main goal of this model is to apply machine learning techniques to make projections of future areas at risk." -> expand to convey what risk means here, how it is measured, etc.

i couldn't easily find how the model is validated, any results we may see, etc.  i would recommend explicitly linking a bunch of that via the readme.rst

**Comment by JannisHoch** [comment]
@soodoku I have updated the readme.md (https://github.com/JannisHoch/copro/commit/9c702d7ef121f877db64c7acfd55e45918ed25e7) . 

Let me know if this clarifies (some of) your questions.

**Comment by JannisHoch** [comment]
additional contextual content in the notebooks was added in https://github.com/JannisHoch/copro/commit/ed3fd13f6d903df415c8d90215046625885525cf

**Comment by soodoku** [comment]
1. fix the spellings etc. "employes" -> "employs" by using something like Grammarly
2. it is good to provide some additional details of the models: what are the Xs (what units), how does train/test split happen, how does hyper-param tuning happen, etc. and useful to give baseline results from your core example model, linking to the data.

**Comment by JannisHoch** [comment]
grammarly used to fix typos in documentatoin and readme in commit 120f1c5812280d2a2acbfbad5634d69961abb101

**Comment by JannisHoch** [comment]
the readme.md file was updated in 0936a8a7e94a89ac141c79c88084e81f1a76af4f.

it contains now a link to the example data stored on Zenodo. The ROC curve based on the example data (as computed in the notebooks) is shown in the readme.md now.

**Comment by JannisHoch** [comment]
i have put more contextual info and explanations about the models in the notebooks with c458f92ad4d2e7b4a4dfb0ef90fe4cfff28483f0.

**Comment by soodoku** [comment]
thanks much @JannisHoch. I think it makes the package more usable more quickly. I am going to ping you again as I run my first model. 

here's one portion that i am struggling w/ in the JOSS ms:

"CoPro is a novel, fully open, and extensible tool to combine the inter-disciplinary expertise required to make long-term projections of conflict risk associated with climatic and environmental drivers. "

I think that line is a bit vague. What is the precise value copro is providing is really useful to convey and something I have struggled to articulate. My hunch = "it is a python packages that makes it *easier* to build and validate models of how climate change predicts conflict locally. it makes it easier by providing some pre-packaged models that can work as starting points, some visualization functions, and ...." see if you can finish that and then put it in the paper and the readme.

**Comment by JannisHoch** [comment]
hi @soodoku, i have tried to make it clearer without being to specific on the technical details. see commit a31963ec475f26d0d3d027b855857c5b6bdf5953.

**Comment by soodoku** [comment]
looks good
