### ISSUE TITLE
software installation/download --- JOSS

### ISSUE THREAD

**Issue by soodoku** [JannisHoch/copro#104]
1. i am surprised that the package is 200 MB. It is unacceptably large for a package that doesn't technically ship any models but ships only the code for how to estimate and validate.  i would recommend finding ways to trim this.

2. ``python setup.py develop`` doesn't work on windows 

```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: cannot import name 'setup'
```

https://stackoverflow.com/questions/32380587/importerror-cannot-import-name-setup

**Comment by JannisHoch** [comment]
@soodoku 
agree that the model package becomes pretty big due to the example data shipped along with the code. 

i have now split the model code and the example data in bc78ac54d35f841a4a80101082598285e039fd0a. the latter can be downloaded now from zenodo (https://zenodo.org/record/4297295).

**Comment by JannisHoch** [comment]
@soodoku 
alright, did not know it was not possible as i work with a consule emulator (cmder) on Win.
have updatedthe documentation in 919f396ef1ecfb5cf323269cfc401484de32bab8.
it is not instructed to use ``pip install -e`` instead, whcih is equivalent to ``python setup.py develop``.

**Comment by soodoku** [comment]
thanks, boss

**Comment by soodoku** [comment]
latest =

```
RROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'E:\\github\\copro\\setup.py'"'"'; __file__='"'"'E:\\github\\copro\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\soodoku\AppData\Local\Temp\pip-pip-egg-info-khbaz47w'
         cwd: E:\github\copro\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\github\copro\setup.py", line 5, in <module>
        from setuptools import setup, find_packages
    ImportError: cannot import name 'setup'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by soodoku** [comment]
if i type
```
python copro_runner.py --help
```

i get

```
python: can't open file 'copro_runner.py': [Errno 2] No such file or directory
```

**Comment by soodoku** [comment]
aight. debugged the first with the help of @suriyan. 

you need to ask people to run the following:

```
pip3 install --upgrade pip setuptools
```

this was not mentioned in the installation directions

```
INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
error: Setup script exited with ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
```

**Comment by JannisHoch** [comment]
hi @soodoku, thanks for your feedback, but I am not sure if I correctly get what you mean.
```
python copro_runner.py --help
```
will only work if you are in the scripts-directory.

Why would I need to update setuptools before?
And where does the GDAL INFO/ERROR originate from? Is this related to setuptools or installing copro?

Thanks for claryfining.

**Comment by JannisHoch** [comment]
by the way, in 6be43521932f3ed8bfd1536f29ab81b5c1392787 I have added a bash-script that downloads the example data from Zenodo. this way it should be relatively straightforward to run the CoPro examples. let me know if this works.

**Comment by JannisHoch** [comment]
hi @soodoku 
i have revamped the model quite a bit in #106.

you can now run CoPro with an executable. To see the documentation, try this.
`copro_runner --help`.

i have also added the debug-info to update setuptools if required.

hope it also works for you :)
