### ISSUE TITLE
Scaling X variable in RF Regression

### ISSUE THREAD

**Issue by Sophiepieternel1** [JannisHoch/copro#178]
Online I find several forums were people say I dont need to scale the X-variables in a RF Regression (e.g. https://stackoverflow.com/questions/8961586/do-i-need-to-normalize-or-scale-data-for-randomforest-r-package). Do you, @JannisHoch or @jensdebruijn , agree? Any more formal/academic source for this?

**Comment by jensdebruijn** [comment]
Yeah, I don't think you need it indeed because of the nature of that algorithm. Don't think you need an academic source for that, just don't mention scaling in the manuscript.

**Comment by JannisHoch** [comment]
From what I understand is that you can do but it will not have much effect.

**Comment by Sophiepieternel1** [comment]
Well, I wont scale them then. I get some very weird negative values for some variables when I scale them.
