### ISSUE TITLE
Deleting folder 'documents'  in migration branch

### ISSUE THREAD

**Issue by Sophiepieternel1** [JannisHoch/copro#181]
@JannisHoch, I am planning to delete the folder docs in the migration branch. It seems to me that all will still be clear then. Would that be ok in your perception?

**Comment by JannisHoch** [comment]
You can do whatever you like on "your" branches ;)

**Comment by Sophiepieternel1** [comment]
Yes sir. I mean, will it still be reproducible to potential reviewers/interested people without that specific folder. I guess it will be

**Comment by JannisHoch** [comment]
@Sophiepieternel is this issue this relevant? if not, please close it. Thanks!
