### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by Sophiepieternel1** [JannisHoch/copro#182]
I gave the new almost final branch the version number 2.0.0, but that might not be consistent with your approach to number the various versions. Or is V2.0.0 ok? @JannisHoch

**Comment by JannisHoch** [comment]
Depends.

 If the functionality of the original copro is still there, you can continue numbering.  Whether it's v2.0.0 or 2.0.0 doesn't really matter, but consistency is appreciated. 

If the old functionality is gone, it would ne good to show that it's a different model, maybe try something like "migration-v1.0.0"

**Comment by Sophiepieternel1** [comment]
Well, you can still use the RF classification option, for when one only want to look at in and out migration (0 = in, 1 = out). Or when you want to look at conflict, but also count conflict (e.g. 1 or 10 conflicts per polygon) and use the RF regressor. but I deleted the other classification options. I think V2.0.0 is than ok, I will change the name than most likely and add these changes to the read me.

**Comment by JannisHoch** [comment]
@Sophiepieternel is this issue this relevant? if not, please close it. Thanks!
